ViTDCNv2_ML_1M_001_8b960980:
    batch_norm: false
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_heads: 1
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_ML_1M_002_f41727ac:
    batch_norm: false
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: LeakyReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_heads: 1
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_ML_1M_003_44163a02:
    batch_norm: false
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: Identity
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_heads: 1
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
