iPinYou_x1_csv_c2b11acf:
    data_format: csv
    data_root: dataset/
    dataset_id: iPinYou_x1_csv
    feature_cols:
    -   active: true
        dtype: str
        name: [weekday, hour, IP, region, city, adexchange, domain, slotid, slotwidth,
            slotheight, slotvisibility, slotformat, creative, advertiser, useragent,
            slotprice]
        type: categorical
    label_col: {dtype: float, name: click}
    min_categr_count: 2
    test_data: dataset/iPinYou/test.csv
    train_data: dataset/iPinYou/train.csv
    valid_data: dataset/iPinYou/test.csv
