DCNv3_iPinYou_x1_001_e6a95d10:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_002_c461c453:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_003_23d65699:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_004_83c0a530:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_005_c461c453:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_006_f65a1220:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_007_ad043351:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_008_b3c40abe:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_009_23d65699:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_010_ad043351:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_011_8747a1a9:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_012_c27b5897:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_013_83c0a530:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 5
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_014_b3c40abe:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 5
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_015_c27b5897:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 5
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_016_cf6f6823:
    batch_norm: true
    batch_size: 40960
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 5
    num_heads: 1
    num_shallow_cross_layers: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
