DCNv3_iPinYou_x1_001_efb3e8cb:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_002_ffa94e10:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_003_280f7138:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_004_ffa94e10:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_005_bd78676d:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_006_fc51f5a3:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_007_280f7138:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 5
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_008_fc51f5a3:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 5
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DCNv3_iPinYou_x1_009_28b6e7a8:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 5
    num_heads: 1
    num_shallow_cross_layers: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
