MaskNet_Criteo_001_145057f5:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.8
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_002_57380f02:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.4
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_003_51edd06e:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_004_47b82aec:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.8
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_005_d970db00:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.4
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_006_be299f8c:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_007_534fd9d8:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.8
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_008_b2204a22:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.4
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_009_ca8b86a8:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_010_e8229162:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.8
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_011_87700df4:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.4
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_012_2a253c18:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_013_175b5621:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.8
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_014_3a2c4f1c:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.4
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_015_ed7c8a62:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: true
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_016_1e664583:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.8
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_017_b76354ec:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.4
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MaskNet_Criteo_018_3b37e4a9:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    emb_layernorm: false
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MaskNet
    model_root: ./checkpoints/
    model_type: SerialMaskNet
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: false
    num_workers: 16
    optimizer: adam
    parallel_block_dim: 500
    parallel_num_blocks: 2
    pickle_feature_encoder: true
    reduction_ratio: 0.1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
