xDeepFM_Movielens_x1_001_e1f9aadc:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_002_2850f022:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.1
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_003_4b34bf2c:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.2
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_004_f025291f:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_005_71580e24:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.1
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_006_42ecda8b:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.2
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_007_2850f022:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_008_c54ff8b5:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.1
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_009_c1cc81f1:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.2
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_010_71580e24:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_011_fc47a260:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.1
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_012_eb3ba6bd:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.2
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_013_4b34bf2c:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_014_c1cc81f1:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.1
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_015_c07403cf:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.2
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_016_42ecda8b:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_017_eb3ba6bd:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.1
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Movielens_x1_018_f985cfb4:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0.2
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
