LR_Movielens_x1_001_4b8cc517:
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-7)
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
LR_Movielens_x1_002_4ef82638:
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-5)
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
LR_Movielens_x1_003_b11f115d:
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-3)
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
LR_Movielens_x1_004_e0dc5a10:
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-1)
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
