FinalNet_Criteo_001_1d448b9f:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.4
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.4
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: false
    use_features: null
    verbose: 1
FinalNet_Criteo_002_883d620e:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.4
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.3
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: false
    use_features: null
    verbose: 1
FinalNet_Criteo_003_883d620e:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.3
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.4
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: false
    use_features: null
    verbose: 1
FinalNet_Criteo_004_81144314:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.3
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.3
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: false
    use_features: null
    verbose: 1
FinalNet_Criteo_005_d64540ca:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.4
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: false
    use_features: null
    verbose: 1
FinalNet_Criteo_006_402cc21e:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.3
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: false
    use_features: null
    verbose: 1
FinalNet_Criteo_007_568ce14b:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.4
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.4
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: true
    use_features: null
    verbose: 1
FinalNet_Criteo_008_49461eb0:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.4
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.3
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: true
    use_features: null
    verbose: 1
FinalNet_Criteo_009_49461eb0:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.3
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.4
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: true
    use_features: null
    verbose: 1
FinalNet_Criteo_010_8b9f476a:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.3
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.3
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: true
    use_features: null
    verbose: 1
FinalNet_Criteo_011_337442a9:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.4
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: true
    use_features: null
    verbose: 1
FinalNet_Criteo_012_af4362ec:
    batch_norm: true
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400, 400]
    block2_dropout: 0.3
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400, 400]
    block_type: 2B
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FinalNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_feature_gating: true
    use_features: null
    verbose: 1
