MLP_iPinYou_x1_001_d0fa70d6:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_002_95ed327e:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_003_98ce9a8d:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_004_d8dca383:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_005_64149574:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_006_1f54288d:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_007_74e882f8:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_008_b6b254e7:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_009_46309c89:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_010_e50695c3:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_011_dc59121c:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_012_0b8f2b55:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_013_46309c89:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_014_e50695c3:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_015_5f0c7cdf:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_016_29866255:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_017_073b67c7:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_018_b1126a31:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_019_6569562b:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
MLP_iPinYou_x1_020_16713cdb:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: MLP
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_dim: 1
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
