SCV_light_loca_adadis_Movielens_x1_001_e1b436d2:
    alpha: 1
    batch_norm: true
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_hops: 2
    num_mask: 6
    num_tower: 6
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.2
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Movielens_x1_002_27aa432a:
    alpha: 1
    batch_norm: true
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    distill_loss: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_hops: 2
    num_mask: 6
    num_tower: 6
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.2
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Movielens_x1_003_b4cbc714:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_hops: 2
    num_mask: 6
    num_tower: 6
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.2
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Movielens_x1_004_1b84921c:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    distill_loss: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_hops: 2
    num_mask: 6
    num_tower: 6
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.2
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
