LogCN_iPinYou_x1_001_d903b75a:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 10}
    monitor_mode: min
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCN_iPinYou_x1_002_e6da408b:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 10}
    monitor_mode: min
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
