GraphFM_Criteo_001_3d44ed41:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 0
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_002_c4d7254d:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 0
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_003_af2fa316:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 1
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_004_04dd1019:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 1
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_005_04dd1019:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 2
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_006_753bbb1e:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 2
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_007_947f08aa:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 3
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_008_4f727822:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 3
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_009_402da3b2:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 4
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_010_562d81f3:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 4
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_011_087c3843:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 5
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_012_3b8c4882:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 5
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_013_4ba6434a:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 6
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_014_3740ba0d:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 6
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_015_02e9de65:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 7
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_016_66250136:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 7
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_017_b7271ebb:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 8
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_018_4b66cf45:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 8
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_019_06306b1d:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 9
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_020_8ac4c183:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 9
    trash2: 2
    use_features: null
    verbose: 1
GraphFM_Criteo_021_897707bf:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 10
    trash2: 1
    use_features: null
    verbose: 1
GraphFM_Criteo_022_061a1e10:
    batch_norm: true
    batch_size: 4096
    block_shape: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dropout_keep_prob: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    heads: 2
    ks: [39, 25, 5]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GraphFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    trash1: 10
    trash2: 2
    use_features: null
    verbose: 1
