FiGNN_iPinYou_x1_001_93cc2081:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 5
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: true
    use_residual: true
    verbose: 1
FiGNN_iPinYou_x1_002_1c3f5fce:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 5
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: true
    use_residual: false
    verbose: 1
FiGNN_iPinYou_x1_003_1c3f5fce:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 5
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: false
    use_residual: true
    verbose: 1
FiGNN_iPinYou_x1_004_d801d63e:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 5
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: false
    use_residual: false
    verbose: 1
FiGNN_iPinYou_x1_005_1fb96b8b:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 7
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: true
    use_residual: true
    verbose: 1
FiGNN_iPinYou_x1_006_963a5367:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 7
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: true
    use_residual: false
    verbose: 1
FiGNN_iPinYou_x1_007_963a5367:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 7
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: false
    use_residual: true
    verbose: 1
FiGNN_iPinYou_x1_008_97957301:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 7
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: false
    use_residual: false
    verbose: 1
FiGNN_iPinYou_x1_009_892afe03:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 10
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: true
    use_residual: true
    verbose: 1
FiGNN_iPinYou_x1_010_14b123bd:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 10
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: true
    use_residual: false
    verbose: 1
FiGNN_iPinYou_x1_011_14b123bd:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 10
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: false
    use_residual: true
    verbose: 1
FiGNN_iPinYou_x1_012_ac1e8f4a:
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gnn_layers: 10
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_gru: false
    use_residual: false
    verbose: 1
