FM_iPinYou_x1_001_ecb79d76:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-7)
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
FM_iPinYou_x1_002_679ed544:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-5)
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
FM_iPinYou_x1_003_4f48a0e0:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-3)
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
FM_iPinYou_x1_004_9505d759:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    regularizer: l2(1e-1)
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
