ViTDCNv3_ML_1M_001_ce617c9c:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_002_d366a015:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_003_51ef2264:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_004_d366a015:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_005_946b81b2:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_006_78db3914:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 3
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_007_51ef2264:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_008_78db3914:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 3
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
ViTDCNv3_ML_1M_009_38f2fbee:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.1
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 4
    num_heads: 1
    num_shallow_cross_layers: 4
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.1
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_patch_size: 8
