SSLViTDCNv3_ML_1M_001_bf381e6c:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 3
    vit_patch_size: 8
    vit_ssl_loss_weight: 1
SSLViTDCNv3_ML_1M_002_fd230900:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 3
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.5
SSLViTDCNv3_ML_1M_003_531389b1:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 3
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.1
SSLViTDCNv3_ML_1M_004_868f2b5b:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 2
    vit_patch_size: 8
    vit_ssl_loss_weight: 1
SSLViTDCNv3_ML_1M_005_286ef32b:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 2
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.5
SSLViTDCNv3_ML_1M_006_d3bbb671:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 2
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.1
SSLViTDCNv3_ML_1M_007_fda854e9:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 1
    vit_patch_size: 8
    vit_ssl_loss_weight: 1
SSLViTDCNv3_ML_1M_008_146f38b4:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 1
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.5
SSLViTDCNv3_ML_1M_009_6b04300a:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 1
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.1
SSLViTDCNv3_ML_1M_010_159b4569:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 0
    vit_patch_size: 8
    vit_ssl_loss_weight: 1
SSLViTDCNv3_ML_1M_011_dd5f4a6c:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 0
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.5
SSLViTDCNv3_ML_1M_012_805fbfe4:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    deep_net_dropout: 0.2
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: SSLViTDCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_regularizer: 0
    num_deep_cross_layers: 2
    num_heads: 1
    num_shallow_cross_layers: 2
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shallow_net_dropout: 0.2
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 2
    vit_num_ssl: 0
    vit_patch_size: 8
    vit_ssl_loss_weight: 0.1
