SCV_light_loca_adadis_Criteo_001_2ca7c470:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_002_f4a61204:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
