xDeepFM_Criteo_001_ee256ed7:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_002_dbd37cd7:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_003_dade8d1b:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_004_f7f240e6:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_005_cee09b39:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_006_feff77ac:
    batch_norm: true
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_007_e153aa47:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_008_df555d9b:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_009_f75325fe:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_010_b69deb98:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_011_a0827e93:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
xDeepFM_Criteo_012_525a6742:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [400, 400, 400]
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    dnn_hidden_units: [400, 400, 400]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    every_x_epochs: 1
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
