AdaGIN_KKBox_x1_001_0594560b:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 0
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_002_478b9a30:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 0
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_003_ab9f4c93:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 1
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_004_3a7e36b5:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 1
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_005_3a7e36b5:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 2
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_006_045d4d6f:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 2
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_007_214a625a:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 3
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_008_36b21f98:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 3
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_009_334ba2b2:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 4
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_010_8de2b695:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 4
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_011_82621db3:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 5
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_012_a1ab777b:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 5
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_013_c9534c2c:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 6
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_014_c24ec7be:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 6
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_015_cb50fec1:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 7
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_016_77103c6a:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 7
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_017_dea7857c:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 8
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_018_6f125d1e:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 8
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_019_003c1cfa:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 9
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_020_92e65fcd:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 9
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_021_33f183a2:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 10
    trash2: 1
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
AdaGIN_KKBox_x1_022_a1f5cd7e:
    batch_norm: true
    batch_size: 10000
    cold_dim: 10
    cold_tau: 0.007
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    fi_hidden_units: [400, 400, 400]
    gnn_layers: 1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AdaGIN
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    trash1: 10
    trash2: 2
    use_features: null
    verbose: 1
    w_hidden_units: [400, 400, 400]
    warm_dim: 10
    warm_tau: 1.15
