LogCNv3_iPinYou_x1_001_a098b927:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_002_02a16b5a:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_003_02a16b5a:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_004_01776d53:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_005_8e0c1951:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_006_071f534f:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_007_071f534f:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_008_df345d76:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_009_8e0c1951:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_010_071f534f:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_011_071f534f:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_012_df345d76:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_013_feefbf85:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_014_99d315c0:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_015_99d315c0:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_016_56fc8053:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: true
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
