SCV_light_loca_adadis_iPinYou_x1_001_b2cfae8a:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_wo_FLE: true
    exp_wo_ReLU: false
    exp_wo_TLE: true
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.5
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_iPinYou_x1_002_00f2d6a3:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_wo_FLE: true
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.5
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_iPinYou_x1_003_00f2d6a3:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: true
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.5
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_iPinYou_x1_004_eb159960:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0.5
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
