ViTDCNv2_iPinYou_x1_001_9b2b493e:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 4
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_002_b560ce44:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_003_c43fde68:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 128
    vit_num_heads: 4
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_004_78c35736:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 128
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_005_500541eb:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 4
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_006_098071e0:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_007_0cdb33b9:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 128
    vit_num_heads: 4
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_008_cc39e2f2:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 128
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_009_d618b2e8:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 4
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_010_7b0e69d8:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 64
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_011_be23280c:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 128
    vit_num_heads: 4
    vit_num_layers: 1
    vit_patch_size: 4
ViTDCNv2_iPinYou_x1_012_24555db9:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_activation: ReLU
    metrics: [logloss, AUC]
    model: ViTDCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_heads: 1
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
    vit_hidden_dim: 128
    vit_num_heads: 8
    vit_num_layers: 1
    vit_patch_size: 4
