SCV_light_loca_adadis_Criteo_001_920c19eb:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_002_a5ab4fd6:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_003_5904fd16:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_004_7222c53b:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_005_b51cf2a9:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_006_2ca7c470:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_007_3a2a1894:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_008_f4a61204:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_009_512fa5a7:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_010_a519b942:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_011_4249aecf:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_012_2fc35a19:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_013_4ef99c70:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_014_236946d0:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 15
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_015_515fea38:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_Criteo_016_f304434a:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: with_bilinear
    dotproduct: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_hops: 1
    num_mask: 5
    num_tower: 20
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
