base_config: ./config/
base_expid: AdaGIN_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    warm_tau: [1.1, 1.15, 1.2]
    cold_tau: [0.007, 0.008]
    gnn_layers: [2, 3, 4]
    net_dropout: [0.2, 0.3]
    batch_norm: [True, False]