base_config: ./config/
base_expid: AFN_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    logarithmic_neurons: [600, 900, 1200, 1500]
    afn_dropout: [0.1, 0.2, 0.3]
    dnn_dropout: [0.1, 0.2, 0.3]
    ensemble_dnn: [True]
    batch_norm: [True]