base_config: ./config/
base_expid: AFN_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    logarithmic_neurons: [1200, 1500]
    afn_dropout: [0.1, 0.2]
    dnn_dropout: [0, 0.1]
    ensemble_dnn: [True, False]
    batch_norm: [True, False]