base_config: ./config/
base_expid: AFN_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    logarithmic_neurons: [600, 800, 1000, 1200]
    afn_dropout: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
    dnn_dropout: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
    ensemble_dnn: [True, False]
    batch_norm: [True, False]