base_config: ./config/
base_expid: AFN_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    logarithmic_neurons: [600, 1200, 2400]
    afn_dropout: [0, 0.1, 0.2]
    dnn_dropout: [0, 0.1, 0.2]
    ensemble_dnn: [True, False]
    batch_norm: [True, False]