base_config: ./config/
base_expid: DCN_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    dnn_hidden_units: [[400, 400, 400]]
    num_cross_layers: [5, 4, 3, 2, 1]
    net_dropout: [0, 0.1, 0.2]
    batch_norm: [True, False]