base_config: ./config/
base_expid: DCN_KKBox_x1
dataset_id: KKBox_x1

tuner_space:
    model_root: './checkpoints/'
    dnn_hidden_units: [[400, 400, 400]]
    num_cross_layers: [5, 4, 3, 2, 1]
    net_dropout: [0, 0.1, 0.2]
    batch_norm: [True, False]