base_config: ./config/
base_expid: DCNv2_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: 4096
    num_cross_layers: [1, 2, 3, 4]
    net_dropout: [0.1]
    batch_norm: [True, False]
    parallel_dnn_hidden_units: [
        [512, 128],
        [512, 256],
        [512, 512]
    ]