base_config: ./config/
base_expid: DCNv2_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: 4096
    num_cross_layers: [2, 3, 4]
    net_dropout: [0.1, 0.2, 0.3]
    batch_norm: [True, False]
    model_structure: ["parallel", "stacked"]
    use_low_rank_mixture: [False]