base_config: ./config/
base_expid: DCNv2_KKBox_x1
dataset_id: KKBox_x1

tuner_space:
    model_root: './checkpoints/'
    num_cross_layers: [1, 2, 3, 4, 5]
    net_dropout: [0.1, 0.2, 0.3]
    batch_norm: [True, False]
    parallel_dnn_hidden_units: [[400, 400, 400]]