base_config: ./config/
base_expid: DCNv2_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    num_cross_layers: [1, 2, 3, 4]
    net_dropout: [0, 0.1]
    batch_norm: [True, False]
    model_structure: ["parallel", "stacked"]
    use_low_rank_mixture: [False]