base_config: ./config/
base_expid: DCNv2_KKBox_x10
dataset_id: KKBox_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: 4096
    num_cross_layers: [1, 2, 3, 4]
    net_dropout: [0.1, 0.2, 0.3]
    parallel_dnn_hidden_units: [
        [512, 128],
        [512, 256],
        [512, 512]
    ]