base_config: ./config/
base_expid: DeepFM_KKBox_x1
dataset_id: KKBox_x1

tuner_space:
    model_root: './checkpoints/'
    net_dropout: [0, 0.1, 0.2]
    batch_norm: [True, False]
    hidden_units: [[400, 400, 400]]