base_config: ./config/
base_expid: DeepFM_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    net_dropout: [0, 0.1, 0.2]
    batch_norm: [True, False]
    hidden_units: [[400, 400, 400]]