base_config: ./config/
base_expid: EulerNet_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    shape: [[10], [20], [30], [20, 20], [30, 30]]
    net_ex_dropout: [0, 0.1, 0.2]
    net_im_dropout: [0, 0.1, 0.2]
    layer_norm: [True, False]
    embedding_dim: 64