base_config: ./config/
base_expid: EulerNet_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    shape: [[10], [10, 10], [20, 20], [20], [39], [39, 39]]
    # shape: [[39], [39, 39]]
    net_ex_dropout: [0.1, 0.2, 0.3]
    net_im_dropout: [0.2, 0.3, 0.4]
    layer_norm: [True]