base_config: ./config/
base_expid: EulerNet_KKBox_x1
dataset_id: KKBox_x1

tuner_space:
    model_root: './checkpoints/'
    shape: [[10], [10, 10], [20, 20], [20], [39], [39, 39]]
    net_ex_dropout: [0, 0.1, 0.2]
    net_im_dropout: [0, 0.1, 0.2]
    layer_norm: [True, False]
    