base_config: ./config/
base_expid: EulerNet_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    shape: [[10], [30], [50]]
    net_ex_dropout: [0, 0.1, 0.2]
    net_im_dropout: [0, 0.1, 0.2]
    layer_norm: [True, False]