base_config: ./config/
base_expid: EulerNet_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    shape: [[20], [20, 20], [35], [35, 35], [50], [50, 50]]
    net_ex_dropout: [0, 0.1, 0.2]
    net_im_dropout: [0, 0.1, 0.2]