base_config: ./config/
base_expid: FiGNN_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    gnn_layers: [5, 7, 10]
    use_gru: [True, False]
    use_residual: [True, False]