base_config: ./config/
base_expid: FiGNN_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    gnn_layers: [5, 7, 10]
    use_gru: [True, False]
    use_residual: [True, False]

