base_config: ./config/
base_expid: FinalMLP_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    use_fs: [True]
    num_heads: [20, 50]
    mlp1_dropout: [0.1, 0.2, 0.3]
    mlp2_dropout: [0.1, 0.2, 0.3]
    mlp1_hidden_units: [[1000, 1000, 1000], [400, 400, 400]]
    mlp2_hidden_units: [[1000, 1000, 1000], [400, 400, 400]]
    