base_config: ./config/
base_expid: FinalNet_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    block_type: "2B"
    batch_norm: True
    embedding_dim: [16]
    use_feature_gating: [True]
    block1_hidden_units: [[1000, 1000, 1000], [1000, 512, 128], [400, 400, 400]]
    block1_dropout: [0.1, 0.2, 0.3, 0.4]
    block2_hidden_units: [[1000, 1000, 1000], [1000, 512, 128], [400, 400, 400]]
    block2_dropout: [0.1, 0.2, 0.3, 0.4]