base_config: ./config/
base_expid: FinalMLP_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_heads: [10, 50, 100]
    mlp1_dropout: [0.1, 0.2]
    mlp2_dropout: [0.1, 0.2]
    monitor_mode: "max"