base_config: ./config/
base_expid: FinalNet_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    monitor_mode: "max"
    block1_dropout: [0.1, 0]
    block2_dropout: [0.1, 0]