base_config: ./config/
base_expid: GDCN_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_cross_layers: [2, 3, 4]
    net_dropout: [0.1, 0.3, 0.5]
    batch_norm: [True, False]
