base_config: ./config/
base_expid: GNNv3_v11_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [2, 3, 4, 5]
    net_dropout: [0.1, 0.2]
    num_hops: [1, 2, 3]
    embedding_dim: [16]
    batch_norm: [True]
    layer_norm: [True, False]
    monitor_mode: "max"