base_config: ./config/
base_expid: GNNv3_v3_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_hops: [3, 4, 5]
    pooling_type: ["mean"]
    net_dropout: [0.3, 0.4, 0.5]
    num_mask: [3, 4, 5]
    use_same_adj: [False]
    embedding_dim: [16]
    batch_norm: [False]
    layer_norm: [False]
    pooling_dim: [2]
    num_tower: [1, 2]
    monitor_mode: "max"