base_config: ./config/
base_expid: GNNv3_v14_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    num_tower: [3, 4, 5, 6, 7, 8]
    net_dropout: [0]
    num_hops: [1]
    num_mask: [2, 3, 4, 5, 6, 7]
    embedding_dim: [16]
    batch_norm: [True, False]
    use_bilinear_fusion: [true]
    pooling_method: ["attn"]
    monitor_mode: "max"