base_config: ./config/
base_expid: GNNv1_v1_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_hops: [2]
    pooling_type: ["mean"]
    net_dropout: [0, 0.1]
    batch_norm: [False]
    layer_norm: [False]
    pooling_dim: [1, 2]
    num_tower: [1, 2]
    monitor_mode: "max"