base_config: ./config/
base_expid: GNNv3_v12_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [15, 16, 17]
    net_dropout: [0, 0.1]
    num_hops: [1, 2]
    num_mask: [3, 4, 5]
    embedding_dim: [16]
    batch_norm: [True]
    pooling_method: ["attn", "mean"]
    edge_pertub_prob: [0]
    monitor_mode: "max"