base_config: ./config/
base_expid: GNNv3_v8_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [2, 3, 4]
    pooling_type: ["mean"]
    net_dropout: [0.6]
    num_mask: [2, 3, 4]
    num_hops: [1, 2]
    embedding_dim: [16]
    batch_norm: [False]
    layer_norm: [False]
    pooling_dim: [2]
    monitor_mode: "max"