base_config: ./config/
base_expid: GNNv3_v10_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [2, 3, 4, 5, 6, 7]
    net_dropout: [0.2]
    num_hops: [2, 3, 4, 5, 6, 7]
    embedding_dim: [16]
    batch_norm: [True, False]
    layer_norm: [True]
    pooling_dim: [2]
    fusion_type: ["ATTN"]
    monitor_mode: "max"