base_config: ./config/
base_expid: GNNv3_v14_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    num_tower: [3, 4, 5, 6, 7]
    net_dropout: [0.3, 0.4, 0.5]
    num_hops: [1, 2, 3]
    num_mask: [3, 4, 5, 6]
    embedding_dim: [16]
    batch_norm: [True, False]
    use_bilinear_fusion: [True]