base_config: ./config/
base_expid: GNNv1_v6_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_hops: [2, 3, 4]
    pooling_type: ["mean"]
    net_dropout: [0, 0.1, 0.2]
    num_mask: [2, 3]
    use_same_adj: [False]
    embedding_dim: [16]
    batch_norm: [False]
    layer_norm: [False]
    pooling_dim: [2]
    num_tower: [1]
    monitor_mode: "max"