base_config: ./config/
base_expid: GNNv3_v8_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    pooling_type: ["mean"]
    embedding_dim: [16]
    batch_norm: [False]
    layer_norm: [False]
    pooling_dim: [2]
    use_same_adj: [True, False]
    monitor_mode: "max"
    num_tower: [2, 3, 4]
    net_dropout: [0.4, 0.5, 0.6]
    num_mask: [2, 3, 4, 5]
    num_hops: [1, 2]