base_config: ./config/
base_expid: ViTDCNv3_ML_1M
dataset_id: ML_1M_7_x1

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_deep_cross_layers: [2, 3, 4]
    num_shallow_cross_layers: [2, 3, 4]
    deep_net_dropout: [0.1]
    shallow_net_dropout: [0.1]
