base_config: ./config/
base_expid: LogCNv6_v3_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_log_layers: [4, 3, 2]
    num_shallow_layers: [4, 3, 2]
    net_dropout: [0]
    batch_norm: [False]
    layer_norm: [True, False]
    output_log: [True]
    exp_layer_norm_before_concat: [True, False]
    exp_distill_loss: [True, False]
    parallel_dnn_hidden_units: [[400, 400, 400]]
    monitor_mode: "max"