base_config: ./config/
base_expid: LogCNv3_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_mask_heads: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
    num_mask_blocks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    net_dropout: [0]
    batch_norm: [True]
    output_log: [False, True]
    # batch_norm: [True, False]
    monitor_mode: "max"