base_config: ./config/
base_expid: LogCNv3_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_mask_heads: [2, 1]
    num_mask_blocks: [2, 1]
    net_dropout: [0]
    batch_norm: [True]
    output_log: [False]
    exp_positive_activation: [True, False]
    exp_additional_mask: [True]
    exp_bias_on_final: [False]
    # batch_norm: [True, False]
    monitor_mode: "max"