base_config: ./config/
base_expid: LogCNv6_v1_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_log_layers: [4, 3, 2, 1]
    num_shallow_layers: [4, 3, 2, 1]
    net_dropout: [0]
    batch_norm: [True, False]
    layer_norm: [True, False]
    output_log: [True]
    monitor_mode: "max"