base_config: ./config/
base_expid: LogCNv3_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_mask_heads: [4, 3, 2, 1]
    num_mask_blocks: [4, 3, 2, 1]
    net_dropout: [0.1]
    batch_norm: [True, False]
    layer_norm: [True, False]
    output_log: True
    monitor_mode: "max"