base_config: ./config/
base_expid: LogCNv4_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_mask_heads: [4, 3, 2, 1]
    num_mask_blocks: [4, 3, 2, 1]
    net_dropout: [0, 0.1, 0.2]
    batch_norm: [True, False]
    layer_norm: [True, False]
    output_log: [True]
    monitor_mode: "max"