base_config: ./config/
base_expid: LogCNv6_v5_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_log_layers: [4, 3, 2, 1]
    num_shallow_layers: [4, 3, 2, 1]
    net_dropout: [0]
    log_batch_norm: [True, False]
    log_layer_norm: [True, False]
    exp_batch_norm: [True, False]
    exp_layer_norm: [True, False]
    parallel_dnn_hidden_units: [[400, 400, 400]]