base_config: ./config/
base_expid: LogDCN_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_mask_heads: [3, 2, 1]
    num_mask_blocks: [3, 2, 1]
    net_dropout: [0]
    batch_norm: [True, False]
    layer_norm: [True, False]
    last_batch_norm: [True, False]
    last_layer_norm: [True, False]
    output_log: [True, False]
    parallel_dnn_hidden_units: [
        [400, 400, 400]
    ]
    monitor_mode: "max"