base_config: ./config/
base_expid: LogDCNv2_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    # batch_size: [40960]
    # num_mask_heads: [4, 3, 2, 1]
    num_mask_heads: [4]
    num_mask_blocks: [4]
    net_dropout: [0, 0.2, 0.5]
    batch_norm: [True, False]
    monitor_mode: "max"