base_config: ./config/
base_expid: MaskNet_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    net_dropout: [0, 0.1, 0.2]
    emb_layernorm: [True, False]
    net_layernorm: [True, False]
    dnn_hidden_units: [[400, 400, 400]]
    model_type: ["SerialMaskNet"]
    monitor_mode: "max"