base_config: ./config/
base_expid: MaskNet_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    net_dropout: [0.1, 0.2, 0.3]
    emb_layernorm: [False]
    net_layernorm: [True, False]
    reduction_ratio: [0.8, 0.4, 0.1]
    dnn_hidden_units: [[400, 400, 400]]
    model_type: ["SerialMaskNet"]
    monitor_mode: "max"