base_config: ./config/
base_expid: MaskNet_Avazu
dataset_id: Avazu_x4_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    parallel_num_blocks: [4, 3, 2]
    parallel_block_dim: [400]
    net_dropout: [0, 0.1, 0.2]
    emb_layernorm: [True, False]
    net_layernorm: [True, False]
    dnn_hidden_units: [[400, 400, 400]]
    model_type: ["ParallelMaskNet"]
    monitor_mode: "max"