base_config: ./config/
base_expid: MaskNet_Movielens_x1
dataset_id: Movielens_x1

tuner_space:
    parallel_num_blocks: [4, 3, 2]
    parallel_block_dim: [400]
    net_dropout: [0, 0.1, 0.2]
    emb_layernorm: [True, False]
    net_layernorm: [True, False]
    dnn_hidden_units: [[400, 400, 400]]
    model_type: ["ParallelMaskNet"]
    monitor_mode: "max"