Base:
    model_root: './checkpoints/'
    num_workers: 16
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null
    dataset_id: Movielens_x1
    optimizer: adam
    loss: 'binary_crossentropy'
    task: binary_classification
    metrics: [logloss, AUC]
    model_root: './checkpoints/'
    embedding_dim: 16
    embedding_regularizer: 0.01
    learning_rate: 1.e-3
    batch_size: 4096
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    epochs: 100


### Movielens

SCV_light_loca_adadis_Movielens_x1:
    model: SCV_light_loca_adadis
    mask_strategy: product
    use_tower: both
    num_hops: 1
    batch_norm: true
    net_dropout: 0.1
    scv_dropout: 0
    use_bilinear_fusion: true
    net_regularizer: 0
    num_tower: 6
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    shuffle: true
    use_features: null
    verbose: 1
    num_mask: 4
    alpha: 0.7
    pooling_method: attn
    distill_loss: true
    subs_origin_loss: false