Base:
    model_root: './checkpoints/'
    num_workers: 8
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null


GDCN_default: # This is a config template
    model: GDCNP
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 32
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DCNv2_KKBox_x10:
    model: DCNv2
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_cross_layers: 3
    net_dropout: 0.1
    parallel_dnn_hidden_units: [512, 128]
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ViTDCNv2_KKBox_x10:
    model: ViTDCNv2
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_cross_layers: 3
    net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    parallel_dnn_hidden_units: [512, 128]
    layer_norm: True
    batch_norm: False
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    mask_activation: "ReLU"
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

DCNv3_KKBox_x10:
    model: DCNv3
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


ViTDCNv3_KKBox_x10:
    model: ViTDCNv3
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'



ViTLinDCNv3_KKBox_x10:
    model: ViTLinDCNv3
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'



ViTExpDCNv3_KKBox_x10:
    model: ViTExpDCNv3
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

DCNv2_ML_1M:
    model: DCNv2
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_cross_layers: 3
    net_dropout: 0.1
    parallel_dnn_hidden_units: [512, 128]
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


DCNv3_ML_1M:
    model: DCNv3
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 2
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


ViTDCNv2_ML_1M:
    model: ViTDCNv2
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_cross_layers: 3
    net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    parallel_dnn_hidden_units: [512, 128]
    layer_norm: True
    batch_norm: False
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    mask_activation: "ReLU"
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

IGDCNv3_ML_1M:
    model: IGDCNv3
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 2
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    


SSLViTDCNv3_ML_1M:
    model: SSLViTDCNv3
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 2
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    vit_num_ssl: 2
    vit_ssl_loss_weight: 1
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

SSLViTDCNv2_ML_1M:
    model: SSLViTDCNv2
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_cross_layers: 3
    net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    vit_num_ssl: 2
    vit_ssl_loss_weight: 1
    layer_norm: True
    batch_norm: False
    num_heads: 1
    parallel_dnn_hidden_units: [512, 128]
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ViTDCNv3_ML_1M:
    model: ViTDCNv3
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 2
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ViTDCNv3Heavy_ML_1M:
    model: ViTDCNv3Heavy
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    layer_norm: True
    batch_norm: True
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 10
    vit_after_steps: 0
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    vit_detach_param: False

ViTLinDCNv3_ML_1M:
    model: ViTLinDCNv3
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 2
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'



ViTExpDCNv3_ML_1M:
    model: ViTExpDCNv3
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 2
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

GDCN_ML_1M:
    model: GDCNP
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0.5
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


# * iPinYou
ViTDCNv3Heavy_iPinYou_x1:
    model: ViTDCNv3Heavy
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    layer_norm: True
    batch_norm: True
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 10
    vit_after_steps: 0
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
    vit_detach_param: False

DCNv3_iPinYou_x1:
    model: DCNv3
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'



ViTDCNv2_iPinYou_x1:
    model: ViTDCNv2
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_cross_layers: 3
    net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    parallel_dnn_hidden_units: [512, 128]
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    mask_activation: "ReLU"
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'



ViTLinDCNv3_iPinYou_x1:
    model: ViTLinDCNv3
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 2
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.1
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


DCNv2_iPinYou_x1:
    model: DCNv2
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4    
    num_cross_layers: 3
    net_dropout: 0.1
    parallel_dnn_hidden_units: [512, 128]
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


ViTDCNv3Heavy_iPinYou_x1:
    model: ViTDCNv3Heavy
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    layer_norm: True
    batch_norm: True
    vit_patch_size: 8
    vit_hidden_dim: 64
    vit_num_layers: 2
    vit_num_heads: 8
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 16
    vit_after_steps: 0
    vit_detach_param: False
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


GDCN_iPinYou_x1:
    model: GDCNP
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0.5
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

# * Criteo

DCNv3_Criteo:
    model: DCNv3
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    layer_norm: True
    batch_norm: False
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

