base_config: ./config/
base_expid: ONN_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    net_dropout: [0.1, 0.2, 0.3, 0.4]
    batch_norm: [false]
    hidden_units: [[400, 400, 400]]