base_config: ./config/
base_expid: PGAResNet_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 40960
    learning_rate: 1.e-3
    resnet_freeze: [True, False]
    resnet_initialize: [True]
    num_deep_cross_layers: [5, 4, 3, 2, 1]
    num_shallow_cross_layers: [5, 4, 3, 2, 1]
    deep_net_dropout: [0.1]
    shallow_net_dropout: [0.2]
    resnet_pretrain: [True, False]
    mask_with_bias: [False]
    num_workers: 16
    resnet_detach_param: [True, False]
