base_config: ./config/
base_expid: PGAViT_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 40960
    learning_rate: 1.e-3
    num_deep_cross_layers: [5, 4, 3, 2]
    num_shallow_cross_layers: [1, 2, 3, 4]
    deep_net_dropout: [0.1]
    shallow_net_dropout: [0.2]
    vit_patch_size: [8]
    vit_hidden_dim: [32, 64, 128]
    vit_num_layers: [1, 2]
    mask_with_bias: [True, False]
    exp_mask_layer_cnt: ["single", "multiple", "none"]
    sha_mask_layer_cnt: ["single", "multiple", "none"]
    vit_num_heads: [8]
    vit_after_steps: [0]
    num_workers: 16
    vit_detach_param: [True]
