base_config: ./config/
base_expid: SCV_light_loca_adadis_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [15, 20]
    net_dropout: [0.2]
    num_hops: [1]
    num_mask: [5]
    embedding_dim: [16]
    batch_norm: [True]
    use_bilinear_fusion: [True]
    distill_loss: ["with_bilinear"]
    subs_origin_loss: [False]
    pooling_method: ["attn"]
    alpha: [0.7]
    dotproduct: [True]