base_config: ./config/
base_expid: SCV_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    num_tower: [2, 3, 4, 5]
    net_dropout: [0.3, 0.4, 0.5]
    scv_dropout: [0.3, 0.4, 0.5]
    num_hops: [1]
    num_mask: [2, 3, 4, 5]
    batch_norm: [True, False]
    gamma: [0.7]
    monitor_mode: "max"