base_config: ./config/
base_expid: SCV_light_loca_adadis_Movielens_x1
dataset_id: Movielens_x1

tuner_space:
    model_root: './checkpoints/'
    num_tower: [1, 2, 3, 4, 5, 6, 7]
    net_dropout: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
    scv_dropout: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
    num_hops: [1, 2, 3]
    num_mask: [1, 2, 3, 4, 5, 6, 7]
    batch_norm: [True, False]
    use_bilinear_fusion: [True]
    distill_loss: [True]
    subs_origin_loss: [False]
    pooling_method: "attn"
    alpha: [0.5, 0.7, 0.9]
    monitor_mode: "max"
    mask_strategy: "product"