base_config: ./config/
base_expid: SCV_KKBox_x1
dataset_id: KKBox_x1

tuner_space:
    model_root: './checkpoints/'
    num_tower: [3, 4, 5, 6]
    net_dropout: [0, 0.1, 0.2]
    scv_dropout: [0, 0.1, 0.2]
    num_hops: [1]
    num_mask: [2, 3, 4, 5]
    batch_norm: [True]
    gamma: [0.9]
    monitor_mode: "max"