base_config: ./config/
base_expid: SCV_light_loca_adadis_Movielens_x1
dataset_id: Movielens_x1

tuner_space:
    model_root: './checkpoints/'
    exp_wo_FLE: [True, False]
    exp_wo_TLE: [True, False]
    trash1: [1, 2, 3, 4, 5]
    trash2: [1, 2, 3, 4]