base_config: ./config/
base_expid: SCV_light_loca_adadis_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [4, 5, 6]
    net_dropout: [0.1, 0.2]
    num_hops: [1]
    num_mask: [2, 3, 4]
    embedding_dim: [16]
    batch_norm: [True]
    use_bilinear_fusion: [True]
    distill_loss: [True, "with_bilinear"]
    subs_origin_loss: [True, False]
    pooling_method: ["attn"]
    alpha: [0.9, 0.7]
    monitor_mode: "max"