base_config: ./config/
base_expid: SCV_heavy_loca_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [6]
    net_dropout: [0.2, 0.3, 0.4, 0.5]
    num_hops: [1]
    embedding_regularizer: [1.e-2, 1.e-3, 1.e-4]
    net_regularizer: [1.e-3, 1.e-4, 1.e-5, 1.e-6]
    num_mask: [2, 3]
    embedding_dim: [16]
    batch_norm: [True, False]
    use_bilinear_fusion: [true]
    distill_loss: [True]
    pooling_method: ["attn"]
    alpha: [0.7]
    monitor_mode: "max"