base_config: ./config/
base_expid: SCV_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: [4096]
    num_tower: [4, 5, 6, 7]
    net_dropout: [0, 0.1, 0.2]      
    num_hops: [1]
    num_mask: [2, 3, 4, 5]
    embedding_dim: [16]
    gamma: [0.7, 0.8]
    monitor_mode: "max"