base_config: ./config/
base_expid: SimCEN_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    cl_temperature: [0.3, 0.4]
    alpha: [0.01, 0.02]
    
    through_dropout: [0.2, 0.3]
    ego_dropout: [0.2, 0.3]
    v1_dropout: [0.2, 0.3]
    v2_dropout: [0.2, 0.3]
    
    ego_batch_norm: [True]
    v1_batch_norm: [True]
    v2_batch_norm: [True]