base_config: ./config/
base_expid: SSLViTDCNv3_ML_1M
dataset_id: ML_1M_7_x1

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_deep_cross_layers: [2]
    num_shallow_cross_layers: [2]
    deep_net_dropout: [0.2]
    shallow_net_dropout: [0.2]
    vit_patch_size: [8]
    vit_hidden_dim: [64]
    vit_num_layers: [2]
    vit_num_heads: [8]
    vit_num_ssl: [3, 2, 1, 0]
    vit_ssl_loss_weight: [1, 0.5, 0.1]
