base_config: ./config/
base_expid: ViTDCNv3Heavy_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_deep_cross_layers: [3, 2]
    num_shallow_cross_layers: [3, 2]
    deep_net_dropout: [0.1]
    shallow_net_dropout: [0.2]
    vit_patch_size: [128, 64, 32]
    vit_hidden_dim: [64]
    vit_num_layers: [1, 2]
    vit_num_heads: [4]
    vit_after_steps: [0, 2, 4]
    num_workers: 4