base_config: ./config/
base_expid: ViTDCNv3Heavy_ML_1M
dataset_id: ML_1M_7_x1

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_deep_cross_layers: [3, 4, 2, 1]
    num_shallow_cross_layers: [3, 4, 2, 1]
    deep_net_dropout: [0.1]
    shallow_net_dropout: [0.2]
    vit_patch_size: [4, 8]
    vit_hidden_dim: [64]
    vit_num_layers: [1, 2]
    vit_num_heads: [4]
    vit_after_steps: [0, 2, 4]
