base_config: ./config/
base_expid: ViTDCNv2_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [1.e-3]
    batch_size: 4096
    num_cross_layers: [4, 3, 2, 1]
    net_dropout: [0.1]
    vit_patch_size: [4]
    vit_hidden_dim: [64, 128]
    vit_num_layers: [1]
    vit_num_heads: [4]