base_config: ./config/
base_expid: xDeepFM_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    batch_norm: [True, False]
    net_dropout: [0, 0.1, 0.2]
    cin_layer_units: [[64, 64, 64], [400, 400, 400]]
