base_config: ./config/
base_expid: xDeepFM_iPinYou_x1
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_norm: [True, False]
    net_dropout: [0.1, 0.2, 0.3]
    cin_layer_units: [[64, 64, 64], [400, 400, 400]]
    embedding_dropout: [0.1, 0.2, 0.3]
