SCV_light_loca_adadis_KKBox_x1_001_5f05e507:
    alpha: 0.9
    batch_norm: true
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    exp_wo_ReLU: false
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 2
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_KKBox_x1_002_6d5143a4:
    alpha: 0.9
    batch_norm: true
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    exp_wo_ReLU: false
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: mean
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 2
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_KKBox_x1_003_bb4d760e:
    alpha: 0.9
    batch_norm: true
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    exp_wo_ReLU: false
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: weighted_sum
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 2
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
SCV_light_loca_adadis_KKBox_x1_004_e19bd506:
    alpha: 0.9
    batch_norm: true
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    exp_wo_ReLU: false
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: inner
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 2
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    use_bilinear_fusion: true
    use_features: null
    use_tower: both
    verbose: 1
