DeepFM_Avazu_001_b64c47c5:
    batch_norm: true
    batch_size: 4096
    dataset_id: Avazu_x4_h5_e3fe560b
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Avazu_002_e8dceac1:
    batch_norm: true
    batch_size: 4096
    dataset_id: Avazu_x4_h5_e3fe560b
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Avazu_003_90d9f61e:
    batch_norm: true
    batch_size: 4096
    dataset_id: Avazu_x4_h5_e3fe560b
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Avazu_004_c81fa707:
    batch_norm: false
    batch_size: 4096
    dataset_id: Avazu_x4_h5_e3fe560b
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Avazu_005_c9bd61d8:
    batch_norm: false
    batch_size: 4096
    dataset_id: Avazu_x4_h5_e3fe560b
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Avazu_006_52044ff8:
    batch_norm: false
    batch_size: 4096
    dataset_id: Avazu_x4_h5_e3fe560b
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
