EulerNet_Criteo_001_8c47baf6:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.1
    net_im_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
EulerNet_Criteo_002_b2b8f08d:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.1
    net_im_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
EulerNet_Criteo_003_b2b8f08d:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.2
    net_im_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
EulerNet_Criteo_004_a6197278:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.2
    net_im_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
EulerNet_Criteo_005_c69331f8:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.1
    net_im_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39, 39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
EulerNet_Criteo_006_2b454564:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.1
    net_im_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39, 39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
EulerNet_Criteo_007_2b454564:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.2
    net_im_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39, 39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
EulerNet_Criteo_008_748ab9ed:
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: EulerNet
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_ex_dropout: 0.2
    net_im_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shape: [39, 39]
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
