DCNv2_ML_1M_001_0892b577:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_002_27c072b7:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_003_d0c44556:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 512]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_004_a6810096:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_005_c74920e6:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_006_9286618c:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 512]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_007_767f973e:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_008_b61a443c:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_009_1a82daff:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 512]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_010_73b40f31:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 128]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_011_40f60927:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_ML_1M_012_56841c29:
    batch_norm: true
    batch_size: 4096
    dataset_id: ML_1M_7_x1_b220bdc8
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [logloss, AUC]
    model: DCNv2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 16
    optimizer: adam
    parallel_dnn_hidden_units: [512, 512]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
