LogCNv5_v2_iPinYou_x1_001_c1fc3938:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_002_3a8f5c52:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_003_3a8f5c52:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_004_f8ada344:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_005_54e043d7:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_006_05338f5c:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_007_05338f5c:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_008_bc3b3f82:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 4
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_009_54e043d7:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_010_05338f5c:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_011_05338f5c:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_012_bc3b3f82:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 4
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_013_205834eb:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_014_5b878bbc:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_015_5b878bbc:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv5_v2_iPinYou_x1_016_232e41e1:
    batch_norm: false
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_add1_before_log: true
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_norm_before_log: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv5_v2
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 3
    num_mask_heads: 3
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
