SCV_light_loca_adadis_Criteo_001_52057b66:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 0
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_002_d10f55ac:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 1
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_003_4af85011:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 2
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_004_df8a6d34:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 3
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_005_bb4a7e91:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 4
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_006_693a0957:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 5
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_007_ef33bd8e:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 6
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_008_16e83e26:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 7
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_009_45cb5e64:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 8
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_010_baabbcbb:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 9
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
SCV_light_loca_adadis_Criteo_011_83089399:
    alpha: 0.7
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    distill_loss: true
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    exp_wo_FLE: false
    exp_wo_ReLU: false
    exp_wo_TLE: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    mask_strategy: product
    metrics: [logloss, AUC]
    model: SCV_light_loca_adadis
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_hops: 1
    num_mask: 4
    num_tower: 7
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    pooling_method: attn
    save_best_only: true
    scv_dropout: 0
    seed: 2024
    shuffle: true
    subs_origin_loss: false
    task: binary_classification
    trash1: 10
    trash2: 1
    use_bilinear_fusion: true
    use_features: null
    verbose: 1
