GNNv3_v12_Criteo_001_2e3d3237:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_002_f20332fb:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_003_58ff30d9:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_004_3824e598:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_005_644f87af:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_006_afbca647:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_007_2c04a393:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_008_bfa62eb2:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_009_cd7519b3:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_010_409d23cc:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 2
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_011_246af534:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_012_2c6f5d4d:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 3
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_013_06316439:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_014_a144f35d:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 4
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_015_7b122bfc:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
GNNv3_v12_Criteo_016_688df920:
    batch_norm: true
    batch_size: 4096
    dataset_id: Criteo_x4_10_h5_49cec1bd
    debug_mode: false
    early_stop_patience: 2
    edge_pertub_prob: 0.1
    embedding_dim: 16
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: GNNv3_v12
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_hops: 1
    num_mask: 3
    num_tower: 5
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: false
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
