DeepFM_KKBox_x1_001_10783a3c:
    batch_norm: true
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_KKBox_x1_002_8917a88d:
    batch_norm: true
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_KKBox_x1_003_8d5ae66b:
    batch_norm: true
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_KKBox_x1_004_a276a27f:
    batch_norm: false
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_KKBox_x1_005_611d0560:
    batch_norm: false
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_KKBox_x1_006_2a369324:
    batch_norm: false
    batch_size: 10000
    dataset_id: KKBox_x1_92d623b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 128
    embedding_regularizer: 0.0005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
