DeepFM_Movielens_x1_001_d4c21276:
    batch_norm: true
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Movielens_x1_002_72a4f96f:
    batch_norm: true
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Movielens_x1_003_9d4a627f:
    batch_norm: true
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Movielens_x1_004_07ff547d:
    batch_norm: false
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Movielens_x1_005_10dd36b2:
    batch_norm: false
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
DeepFM_Movielens_x1_006_4e37fa6a:
    batch_norm: false
    batch_size: 4096
    dataset_id: Movielens_x1_0103c136
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 16
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    task: binary_classification
    use_features: null
    verbose: 1
