from .SCV import SCV
from .SCV_ada_tf import SCV_ada_tf
from .SCV_light_loca import SCV_light_loca
from .SCV_loca import SCV_loca
from .SCV_light_loca_batchnorm import SCV_light_loca_batchnorm
from .SCV_light import SCV_light
from .SCV_heavy_loca import SCV_heavy_loca
from .SCV_light_loca_adadis import SCV_light_loca_adadis
from .SCV_coe import SCV_coe