LogCNv3_iPinYou_x1_001_fff46357:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: true
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_002_e7078e1d:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_003_86330dad:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: true
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_004_47e47394:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 2
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_005_86330dad:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: true
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_006_47e47394:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 2
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_007_805e470f:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: true
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
LogCNv3_iPinYou_x1_008_62881cba:
    batch_norm: true
    batch_size: 4096
    dataset_id: iPinYou_x1_csv_c2b11acf
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    exp_additional_mask: true
    exp_bias_on_final: false
    exp_positive_activation: false
    feature_config: null
    feature_specs: null
    group_id: null
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LogCNv3
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: 0}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    num_mask_blocks: 1
    num_mask_heads: 1
    num_workers: 16
    optimizer: adam
    output_log: false
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2024
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
